# Generated by Django 3.0.2 on 2020-01-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eathquake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField()),
                ('id_info', models.IntegerField()),
                ('src', models.CharField(max_length=50)),
                ('id_eathquake', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('eathquake_time', models.DateTimeField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=18)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=18)),
                ('mag', models.DecimalField(decimal_places=6, max_digits=18)),
                ('depth', models.DecimalField(decimal_places=6, max_digits=18)),
                ('nst', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=2500)),
                ('data_source', models.CharField(max_length=500)),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
