# Generated by Django 3.0.2 on 2020-01-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quakemap', '0002_remove_eathquake_id_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eathquake',
            options={'ordering': ['eathquake_time']},
        ),
    ]
