# Generated by Django 3.0.2 on 2020-01-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quakemap', '0003_auto_20200115_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eathquake',
            name='session_id',
            field=models.CharField(max_length=50),
        ),
    ]
