# Generated by Django 3.0.2 on 2020-01-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quakemap', '0006_auto_20200115_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='eathquake',
            name='url',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
