# Generated by Django 3.0.2 on 2020-01-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quakemap', '0007_eathquake_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='eathquake',
            name='lat_deg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eathquake',
            name='lng_deg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
