# Generated by Django 3.0.2 on 2020-02-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eathquake',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='eathquake',
            name='mag',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
